//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string InterestingFacts { get; set; }
        public byte[] Image { get; set; }
        public string ImageFileName { get; set; }
        public string Sound { get; set; }
    }
}
