//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR16.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PR16DBEntities : DbContext
    {
        public PR16DBEntities()
            : base("name=PR16DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Артикул> Артикул { get; set; }
        public virtual DbSet<ЕдиницыИзмерения> ЕдиницыИзмерения { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<КатегорияТовара> КатегорияТовара { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Производитель> Производитель { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<СписокЗаказов> СписокЗаказов { get; set; }
        public virtual DbSet<СтатусЗаказа> СтатусЗаказа { get; set; }
        public virtual DbSet<ТипТовара> ТипТовара { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
