//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public Nullable<int> Роль_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual Роль Роль { get; set; }
    }
}
