//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокЗаказов
    {
        public int Код { get; set; }
        public int КодАртикула { get; set; }
        public Nullable<int> КодЗаказа { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Артикул Артикул { get; set; }
        public virtual Заказ Заказ { get; set; }
    }
}
