//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public int Код { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<int> ТипТовара { get; set; }
        public Nullable<int> ЕдиницаИзмерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> Поставщик { get; set; }
        public Nullable<int> Производитель { get; set; }
        public Nullable<int> КатегорияТовара { get; set; }
        public Nullable<decimal> ДействующаяСкидка { get; set; }
        public Nullable<int> КолВоНаСкладе { get; set; }
        public string ОписаниеТовара { get; set; }
    
        public virtual Артикул Артикул1 { get; set; }
        public virtual ЕдининицыИзмерения ЕдининицыИзмерения { get; set; }
        public virtual КатегорияТовара КатегорияТовара1 { get; set; }
        public virtual Поставщик Поставщик1 { get; set; }
        public virtual Производитель Производитель1 { get; set; }
        public virtual ТипТовара ТипТовара1 { get; set; }
    }
}
