//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public int Код { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<int> Тип_товара { get; set; }
        public Nullable<int> Единица_измерения { get; set; }
        public Nullable<int> Цена { get; set; }
        public Nullable<int> Поставщик { get; set; }
        public Nullable<int> Производитель { get; set; }
        public Nullable<int> Категория_товара { get; set; }
        public Nullable<int> Действующая_скидка { get; set; }
        public Nullable<int> Кол_во_на_складе { get; set; }
        public string Описание_товара { get; set; }
    
        public virtual Артикул Артикул1 { get; set; }
        public virtual ЕдиницыИзмерения ЕдиницыИзмерения { get; set; }
        public virtual КатегорияТовара КатегорияТовара { get; set; }
        public virtual Поставщик Поставщик1 { get; set; }
        public virtual Производитель Производитель1 { get; set; }
        public virtual ТипТовара ТипТовара { get; set; }
    }
}
